ST_DumpSegments
postgis/postgis pull request #615
Opened 2021-05-17 21:33 UTC by kalenikaliaksandr

2021-05-18 17:40 UTC, kalenikaliaksandr commented on postgis/postgis.sql.in
> +-- Availability: 3.2.0
too optimistic?

2021-05-18 21:07 UTC, Komzpa requested changes

2021-05-18 21:07 UTC, Komzpa commented on postgis/postgis.sql.in
> +-- Availability: 3.2.0
I believe it's ok

2021-05-18 21:07 UTC, Komzpa commented on postgis/lwgeom_dumpsegments.c
> +			if (lwgeom->type == LINETYPE)
Original had triangle too. DumpSegments is also used around constrained Delaunay triangulations, and that means that triangles/TINs can be the thing you try to dump as segments too.

2021-05-19 11:45 UTC, kalenikaliaksandr commented on postgis/lwgeom_dumpsegments.c
> + * ^copyright^
Kontur? :)

2021-05-20 07:11 UTC, Komzpa commented on postgis/lwgeom_dumpsegments.c
> +Datum LWGEOM_dumpsegments(PG_FUNCTION_ARGS);
It's a smaller issue than having the code duplicated IMHO. We can rename the file.

2021-07-12 19:45 UTC, merged